# Setup
title:               Learning curve
tagline:             'An authentic pursuit to rid the imposter in me ðŸ§˜'
description:         'Logging Curiosities and Experiments with ML Tools & Techniques: A Recording of My Learnings. <br><i>Am attempting a Feynman here!</i><br> Journal blog by <a href="https://twitter.com/nishzsche" target="_blank">@nishzsche</a>'
url:                 https://nishzsche.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nishanth R
  url:               https://twitter.com/nishzsche
  email:             nishanthrajamani@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
